# Generated by Django 5.0.6 on 2024-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_recentsearch_departuredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.DurationField(default=''),
        ),
    ]
