# Generated by Django 5.0.6 on 2024-07-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentsearch',
            name='creationDtTm',
        ),
    ]
