# Generated by Django 5.0.6 on 2024-07-31 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_remove_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
