# Generated by Django 5.0.6 on 2024-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
