# Generated by Django 5.0.6 on 2024-07-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.DateField(),
        ),
    ]
