# Generated by Django 5.0.6 on 2024-07-31 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.CharField(default=datetime.date(2024, 7, 31), max_length=100),
        ),
    ]
