# Generated by Django 5.0.6 on 2024-07-31 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_alter_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentsearch',
            old_name='creationDtTm',
            new_name='creationStamp',
        ),
    ]
