# Generated by Django 5.0.6 on 2024-07-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_rename_creationdttm_recentsearch_creationstamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentsearch',
            old_name='creationStamp',
            new_name='creationDtTm',
        ),
    ]
